In [1]:
import pandas as pd

In [2]:
data_path = "data/genie_v13.3/"

In [3]:
#def process_clinical(clinical_file):

In [4]:
clinical_patient_file = "data_clinical_patient_13.3-consortium.txt"
df_clinical_patient = pd.read_csv(f"{data_path}/{clinical_patient_file}", sep="\t", skiprows=4)

clinical_sample_file = "data_clinical_sample_13.3-consortium.txt"
df_clinical_sample = pd.read_csv(f"{data_path}/{clinical_sample_file}", sep="\t", skiprows=4)

cna_file = "data_cna_13.3-consortium.txt"
df_cna = pd.read_csv(f"{data_path}/{cna_file}", sep="\t")

gene_matrix_file = "data_gene_matrix_13.3-consortium.txt"
df_gene_matrix = pd.read_csv(f"{data_path}/{gene_matrix_file}", sep="\t")

mutations_extended_file = "data_mutations_extended_13.3-consortium.txt"
df_mutations_extended = pd.read_csv(f"{data_path}/{mutations_extended_file}", sep="\t")

In [20]:
df_clinical_patient.head()

,PATIENT_ID,SEX,PRIMARY_RACE,SECONDARY_RACE,TERTIARY_RACE,ETHNICITY,BIRTH_YEAR,CENTER,INT_CONTACT,INT_DOD,YEAR_CONTACT,DEAD,YEAR_DEATH
0,GENIE-VICC-101416,Female,White,Not collected,Not collected,Non-Spanish/non-Hispanic,1961,VICC,19225,Not Applicable,2014,False,Not Applicable
1,GENIE-VICC-102225,Female,White,Not collected,Not collected,Non-Spanish/non-Hispanic,1982,VICC,12057,12487,2015,True,2017
2,GENIE-VICC-102424,Female,White,Not collected,Not collected,Non-Spanish/non-Hispanic,1952,VICC,23505,23625,2016,True,2016
3,GENIE-VICC-102966,Male,White,Not collected,Not collected,Non-Spanish/non-Hispanic,1951,VICC,23426,23430,2015,True,2015
4,GENIE-VICC-103244,Female,Unknown,Not collected,Not collected,Unknown,1964,VICC,18267,18311,2014,True,2014

In [9]:
df_clinical_sample.head()

,PATIENT_ID,SAMPLE_ID,AGE_AT_SEQ_REPORT,ONCOTREE_CODE,SAMPLE_TYPE,SEQ_ASSAY_ID,CANCER_TYPE,CANCER_TYPE_DETAILED,AGE_AT_SEQ_REPORT_DAYS,SAMPLE_TYPE_DETAILED,SEQ_YEAR,SAMPLE_CLASS
0,GENIE-VICC-101416,GENIE-VICC-101416-unk-1,52,MAAP,Primary,VICC-01-T7,Appendiceal Cancer,Mucinous Adenocarcinoma of the Appendix,19247,Primary tumor,2014.0,Tumor
1,GENIE-VICC-102225,GENIE-VICC-102225-unk-1,31,READ,Metastasis,VICC-01-T7,Colorectal Cancer,Rectal Adenocarcinoma,11589,Metastasis site unspecified,2014.0,Tumor
2,GENIE-VICC-102424,GENIE-VICC-102424-unk-1,63,SCCNOS,Metastasis,VICC-01-T7,Cancer of Unknown Primary,"Squamous Cell Carcinoma, NOS",23302,Metastasis site unspecified,2015.0,Tumor
3,GENIE-VICC-102966,GENIE-VICC-102966-unk-1,64,LUAD,Metastasis,VICC-01-T7,Non-Small Cell Lung Cancer,Lung Adenocarcinoma,23390,Metastasis site unspecified,2015.0,Tumor
4,GENIE-VICC-103244,GENIE-VICC-103244-unk-1,50,IDC,Primary,VICC-01-T5A,Breast Cancer,Breast Invasive Ductal Carcinoma,18284,Primary tumor,2014.0,Tumor

In [15]:
len(df_clinical_sample["PATIENT_ID"].unique())

146565

In [19]:
23741/365

65.04383561643836

In [24]:
df_mutations_extended[df_mutations_extended["Tumor_Sample_Barcode"]=="GENIE-MSK-P-0022122-T06-IH3"].head()

,Hugo_Symbol,Entrez_Gene_Id,Center,NCBI_Build,Chromosome,Start_Position,End_Position,Strand,Consequence,Variant_Classification,...,FILTER,Polyphen_Prediction,Polyphen_Score,SIFT_Prediction,SIFT_Score,SWISSPROT,n_depth,t_depth,Annotation_Status,mutationInCis_Flag
758752,SRSF2,6427.0,MSK,GRCh37,17,74732959,74732959,+,missense_variant,Missense_Mutation,...,NaN,probably_damaging,0.987,tolerated,0.12,NaN,485.0,277.0,SUCCESS,False
818623,DNMT3A,1788.0,MSK,GRCh37,2,25463248,25463248,+,missense_variant,Missense_Mutation,...,NaN,probably_damaging,0.963,deleterious,0.00,NaN,1233.0,978.0,SUCCESS,False

In [26]:
df_cna.head()

,Hugo_Symbol,GENIE-DFCI-002910-3355,GENIE-DFCI-003035-3760,GENIE-DFCI-003337-817,GENIE-DFCI-001601-3485,GENIE-DFCI-000578-250,GENIE-DFCI-004466-422,GENIE-DFCI-004327-47,GENIE-DFCI-003498-202,GENIE-DFCI-002153-155,...,GENIE-WAKE-F1421-01,GENIE-WAKE-F1422-01,GENIE-WAKE-F1423-01,GENIE-WAKE-F1424-01,GENIE-WAKE-F1425-01,GENIE-WAKE-F1426-01,GENIE-WAKE-F1428-01,GENIE-WAKE-F1429-01,GENIE-WAKE-F1430-01,GENIE-WAKE-F1431-01
0,ABCB11,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,ABL1,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,ABL2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,ACTB,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,ACTG1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [34]:
df_cna[samples].describe()

,GENIE-MSK-P-0022122-T06-IH3,GENIE-MSK-P-0022122-T07-IH3,GENIE-MSK-P-0022122-T12-IM6,GENIE-MSK-P-0022122-T13-IH3,GENIE-MSK-P-0022122-T14-IH3,GENIE-MSK-P-0022122-T15-IH3,GENIE-MSK-P-0022122-T11-IH3,GENIE-MSK-P-0022122-T16-IH3,GENIE-MSK-P-0022122-T17-IH3,GENIE-MSK-P-0022122-T19-IH3,GENIE-MSK-P-0022122-T20-IH3,GENIE-MSK-P-0022122-T21-IH3
count,409.0,409.0,505.0,409.0,409.0,409.0,409.0,409.0,409.0,409.000000,409.000000,409.000000
mean,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-0.044010,-0.029340,-0.044010
std,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.293758,0.341737,0.293758
min,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-2.000000,-2.000000,-2.000000
25%,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000
50%,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000
75%,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000
max,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,2.000000,0.000000

In [41]:
df_cna[["Hugo_Symbol"]+samples].head()

,Hugo_Symbol,GENIE-MSK-P-0022122-T06-IH3,GENIE-MSK-P-0022122-T07-IH3,GENIE-MSK-P-0022122-T12-IM6,GENIE-MSK-P-0022122-T13-IH3,GENIE-MSK-P-0022122-T14-IH3,GENIE-MSK-P-0022122-T15-IH3,GENIE-MSK-P-0022122-T11-IH3,GENIE-MSK-P-0022122-T16-IH3,GENIE-MSK-P-0022122-T17-IH3,GENIE-MSK-P-0022122-T19-IH3,GENIE-MSK-P-0022122-T20-IH3,GENIE-MSK-P-0022122-T21-IH3
0,ABCB11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,ABL1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,ABL2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,ACTB,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,ACTG1,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0

In [25]:
df_gene_matrix.head()

                 SAMPLE_ID    mutations          cna
0  GENIE-VICC-101416-unk-1   VICC-01-T7   VICC-01-T7
1  GENIE-VICC-102225-unk-1   VICC-01-T7   VICC-01-T7
2  GENIE-VICC-102424-unk-1   VICC-01-T7   VICC-01-T7
3  GENIE-VICC-102966-unk-1   VICC-01-T7   VICC-01-T7
4  GENIE-VICC-103244-unk-1  VICC-01-T5A  VICC-01-T5A

In [ ]:
df_mutations_extended[df_mutations_extended["Tumor_Sample_Barcode"]=="GENIE-MSK-P-0022122-T06-IH3"].head()

In [30]:
samples = list(df_clinical_sample[df_clinical_sample["PATIENT_ID"]=="GENIE-MSK-P-0022122"]["SAMPLE_ID"].unique())

In [18]:
df_clinical_sample[df_clinical_sample["PATIENT_ID"]=="GENIE-MSK-P-0022122"]

,PATIENT_ID,SAMPLE_ID,AGE_AT_SEQ_REPORT,ONCOTREE_CODE,SAMPLE_TYPE,SEQ_ASSAY_ID,CANCER_TYPE,CANCER_TYPE_DETAILED,AGE_AT_SEQ_REPORT_DAYS,SAMPLE_TYPE_DETAILED,SEQ_YEAR,SAMPLE_CLASS
76994,GENIE-MSK-P-0022122,GENIE-MSK-P-0022122-T06-IH3,64,MDS,Primary,MSK-IMPACT-HEME-400,Myelodysplastic Syndromes,Myelodysplastic Syndromes,23741,Primary tumor,2018.0,Tumor
76995,GENIE-MSK-P-0022122,GENIE-MSK-P-0022122-T07-IH3,64,MDS,Primary,MSK-IMPACT-HEME-400,Myelodysplastic Syndromes,Myelodysplastic Syndromes,23741,Primary tumor,2018.0,Tumor
76996,GENIE-MSK-P-0022122,GENIE-MSK-P-0022122-T12-IM6,65,PTAD,Primary,MSK-IMPACT468,Sellar Tumor,Pituitary Adenoma,24106,Primary tumor,2019.0,Tumor
76997,GENIE-MSK-P-0022122,GENIE-MSK-P-0022122-T13-IH3,65,MDSEB1,Primary,MSK-IMPACT-HEME-400,Myelodysplastic Syndromes,MDS with excess blasts-1,24106,Primary tumor,2019.0,Tumor
76998,GENIE-MSK-P-0022122,GENIE-MSK-P-0022122-T14-IH3,67,MDSEB,Primary,MSK-IMPACT-HEME-400,Myelodysplastic Syndromes,MDS with Excess Blasts,24472,Primary tumor,2019.0,Tumor
76999,GENIE-MSK-P-0022122,GENIE-MSK-P-0022122-T15-IH3,67,MDSEB,Metastasis,MSK-IMPACT-HEME-400,Myelodysplastic Syndromes,MDS with Excess Blasts,24472,Metastasis site unspecified,2019.0,Tumor
77000,GENIE-MSK-P-0022122,GENIE-MSK-P-0022122-T11-IH3,65,MDSEB1,Primary,MSK-IMPACT-HEME-400,Myelodysplastic Syndromes,MDS with excess blasts-1,24106,Primary tumor,2018.0,Tumor
77001,GENIE-MSK-P-0022122,GENIE-MSK-P-0022122-T16-IH3,68,MDSEB1,Unspecified,MSK-IMPACT-HEME-400,Myelodysplastic Syndromes,MDS with excess blasts-1,24837,Not otherwise specified,2020.0,Tumor
77002,GENIE-MSK-P-0022122,GENIE-MSK-P-0022122-T17-IH3,68,AML,Unspecified,MSK-IMPACT-HEME-400,Leukemia,Acute Myeloid Leukemia,24837,Not otherwise specified,2020.0,Tumor
77003,GENIE-MSK-P-0022122,GENIE-MSK-P-0022122-T19-IH3,68,AML,Unspecified,MSK-IMPACT-HEME-400,Leukemia,Acute Myeloid Leukemia,24837,Not otherwise specified,2020.0,Tumor
77004,GENIE-MSK-P-0022122,GENIE-MSK-P-0022122-T20-IH3,68,AMLMRC,Unspecified,MSK-IMPACT-HEME-400,Leukemia,AML with Myelodysplasia-Related Changes,24837,Not otherwise specified,2020.0,Tumor
77005,GENIE-MSK-P-0022122,GENIE-MSK-P-0022122-T21-IH3,68,AML,Unspecified,MSK-IMPACT-HEME-400,Leukemia,Acute Myeloid Leukemia,24837,Not otherwise specified,2020.0,Tumor

In [75]:
df_clinical_sample["PATIENT_ID"].value_counts().value_counts()

1     133792
2       9909
3       1742
4        506
5        212
6        132
7         83
8         62
9         44
10        32
11        20
12         9
13         9
15         5
14         4
17         2
16         1
19         1
Name: PATIENT_ID, dtype: int64

In [50]:
len(df_mutations_extended[df_mutations_extended["Hugo_Symbol"]=="NF1"])

11622

In [53]:
nf1_mutations = list(df_mutations_extended[df_mutations_extended["Hugo_Symbol"]=="NF1"]["Tumor_Sample_Barcode"].unique())

In [55]:
len(df_clinical_sample[df_clinical_sample["SAMPLE_ID"].isin(nf1_mutations)]["PATIENT_ID"].unique())

8312

In [56]:
patients_nf1 = list(df_clinical_sample[df_clinical_sample["SAMPLE_ID"].isin(nf1_mutations)]["PATIENT_ID"].unique())

In [63]:
df_clinical_sample[df_clinical_sample["PATIENT_ID"].isin(patients_nf1)]["PATIENT_ID"].value_counts()

GENIE-MSK-P-0034548      12
GENIE-MSK-P-0038701      11
GENIE-MSK-P-0038400      10
GENIE-MSK-P-0046428      10
GENIE-MSK-P-0044679       9
                         ..
GENIE-VICC-160548         1
GENIE-VICC-157057         1
GENIE-VICC-138764         1
GENIE-VICC-112376         1
GENIE-PROV-36d1bb1a22     1
Name: PATIENT_ID, Length: 8312, dtype: int64

In [68]:
patients_ids = list(df_clinical_sample[df_clinical_sample["PATIENT_ID"].isin(patients_nf1)]["PATIENT_ID"].value_counts().index)

In [69]:
patient_id = patients_ids[1]

In [70]:
samples = list(df_clinical_sample[df_clinical_sample["PATIENT_ID"]==patient_id]["SAMPLE_ID"].unique())

In [71]:
df_cna[samples].describe()

,GENIE-MSK-P-0038701-T02-IH3,GENIE-MSK-P-0038701-T03-IH3,GENIE-MSK-P-0038701-T04-IH3,GENIE-MSK-P-0038701-T05-IH3,GENIE-MSK-P-0038701-T06-IH3,GENIE-MSK-P-0038701-T07-IH3,GENIE-MSK-P-0038701-T08-IH3,GENIE-MSK-P-0038701-T09-IH3,GENIE-MSK-P-0038701-T10-IH3,GENIE-MSK-P-0038701-T11-IH3,GENIE-MSK-P-0038701-T12-IH3
count,409.0,409.0,409.0,409.0,409.0,409.0,409.0,409.0,409.0,409.0,409.0
mean,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
std,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
min,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
25%,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
50%,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
75%,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
max,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [73]:
df_clinical_sample[df_clinical_sample["PATIENT_ID"]==patient_id]

,PATIENT_ID,SAMPLE_ID,AGE_AT_SEQ_REPORT,ONCOTREE_CODE,SAMPLE_TYPE,SEQ_ASSAY_ID,CANCER_TYPE,CANCER_TYPE_DETAILED,AGE_AT_SEQ_REPORT_DAYS,SAMPLE_TYPE_DETAILED,SEQ_YEAR,SAMPLE_CLASS
93863,GENIE-MSK-P-0038701,GENIE-MSK-P-0038701-T02-IH3,Unknown,AML,Primary,MSK-IMPACT-HEME-400,Leukemia,Acute Myeloid Leukemia,Unknown,Primary tumor,2019.0,Tumor
93864,GENIE-MSK-P-0038701,GENIE-MSK-P-0038701-T03-IH3,Unknown,AML,Primary,MSK-IMPACT-HEME-400,Leukemia,Acute Myeloid Leukemia,Unknown,Primary tumor,2019.0,Tumor
93865,GENIE-MSK-P-0038701,GENIE-MSK-P-0038701-T04-IH3,Unknown,AMLCEBPA,Primary,MSK-IMPACT-HEME-400,Leukemia,AML with Biallelic Mutations of CEBPA,Unknown,Primary tumor,2019.0,Tumor
93866,GENIE-MSK-P-0038701,GENIE-MSK-P-0038701-T05-IH3,Unknown,AML,Primary,MSK-IMPACT-HEME-400,Leukemia,Acute Myeloid Leukemia,Unknown,Primary tumor,2019.0,Tumor
93867,GENIE-MSK-P-0038701,GENIE-MSK-P-0038701-T06-IH3,Unknown,AMLCEBPA,Primary,MSK-IMPACT-HEME-400,Leukemia,AML with Biallelic Mutations of CEBPA,Unknown,Primary tumor,2019.0,Tumor
93868,GENIE-MSK-P-0038701,GENIE-MSK-P-0038701-T07-IH3,Unknown,AML,Primary,MSK-IMPACT-HEME-400,Leukemia,Acute Myeloid Leukemia,Unknown,Primary tumor,2019.0,Tumor
93869,GENIE-MSK-P-0038701,GENIE-MSK-P-0038701-T08-IH3,Unknown,AMLCEBPA,Metastasis,MSK-IMPACT-HEME-400,Leukemia,AML with Biallelic Mutations of CEBPA,Unknown,Metastasis site unspecified,2019.0,Tumor
93870,GENIE-MSK-P-0038701,GENIE-MSK-P-0038701-T09-IH3,Unknown,AMLCEBPA,Metastasis,MSK-IMPACT-HEME-400,Leukemia,AML with Biallelic Mutations of CEBPA,Unknown,Metastasis site unspecified,2020.0,Tumor
93871,GENIE-MSK-P-0038701,GENIE-MSK-P-0038701-T10-IH3,Unknown,AMLCEBPA,Unspecified,MSK-IMPACT-HEME-400,Leukemia,AML with Biallelic Mutations of CEBPA,Unknown,Not otherwise specified,2020.0,Tumor
93872,GENIE-MSK-P-0038701,GENIE-MSK-P-0038701-T11-IH3,Unknown,AMLNOS,Unspecified,MSK-IMPACT-HEME-400,Leukemia,"AML, NOS",Unknown,Not otherwise specified,2020.0,Tumor
93873,GENIE-MSK-P-0038701,GENIE-MSK-P-0038701-T12-IH3,Unknown,AML,Unspecified,MSK-IMPACT-HEME-400,Leukemia,Acute Myeloid Leukemia,Unknown,Not otherwise specified,2021.0,Tumor

In [79]:
df_mutations_extended[df_mutations_extended["Tumor_Sample_Barcode"].isin(samples)]

,Hugo_Symbol,Entrez_Gene_Id,Center,NCBI_Build,Chromosome,Start_Position,End_Position,Strand,Consequence,Variant_Classification,...,FILTER,Polyphen_Prediction,Polyphen_Score,SIFT_Prediction,SIFT_Score,SWISSPROT,n_depth,t_depth,Annotation_Status,mutationInCis_Flag
392661,WT1,7490.0,MSK,GRCh37,11,32414263,32414263,+,stop_gained,Nonsense_Mutation,...,NaN,NaN,NaN,NaN,NaN,NaN,1131.0,1039.0,SUCCESS,False
412791,CEBPA,1050.0,MSK,GRCh37,19,33793062,33793063,+,frameshift_variant,Frame_Shift_Ins,...,NaN,NaN,NaN,NaN,NaN,NaN,507.0,396.0,SUCCESS,False
603595,CEBPA,1050.0,MSK,GRCh37,19,33792384,33792385,+,inframe_insertion,In_Frame_Ins,...,NaN,NaN,NaN,NaN,NaN,NaN,1385.0,1376.0,SUCCESS,False
651530,WT1,7490.0,MSK,GRCh37,11,32414263,32414263,+,stop_gained,Nonsense_Mutation,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,864.0,SUCCESS,False
863718,NF1,4763.0,MSK,GRCh37,17,29579972,29579972,+,frameshift_variant,Frame_Shift_Del,...,NaN,NaN,NaN,NaN,NaN,NaN,990.0,1007.0,SUCCESS,False

In [78]:
df_mutations_extended[df_mutations_extended["Tumor_Sample_Barcode"].isin(samples)].groupby("Tumor_Sample_Barcode")["Hugo_Symbol"].unique()

Tumor_Sample_Barcode
GENIE-MSK-P-0038701-T02-IH3    [WT1, CEBPA, NF1]
GENIE-MSK-P-0038701-T05-IH3                [WT1]
Name: Hugo_Symbol, dtype: object

In [49]:
df_mutations_extended[df_mutations_extended["Tumor_Sample_Barcode"]=="GENIE-MSK-P-0022122-T06-IH3"].head()

,Hugo_Symbol,Entrez_Gene_Id,Center,NCBI_Build,Chromosome,Start_Position,End_Position,Strand,Consequence,Variant_Classification,...,FILTER,Polyphen_Prediction,Polyphen_Score,SIFT_Prediction,SIFT_Score,SWISSPROT,n_depth,t_depth,Annotation_Status,mutationInCis_Flag
758752,SRSF2,6427.0,MSK,GRCh37,17,74732959,74732959,+,missense_variant,Missense_Mutation,...,NaN,probably_damaging,0.987,tolerated,0.12,NaN,485.0,277.0,SUCCESS,False
818623,DNMT3A,1788.0,MSK,GRCh37,2,25463248,25463248,+,missense_variant,Missense_Mutation,...,NaN,probably_damaging,0.963,deleterious,0.00,NaN,1233.0,978.0,SUCCESS,False

In [10]:
df_mutations_extended.head()

,Hugo_Symbol,Entrez_Gene_Id,Center,NCBI_Build,Chromosome,Start_Position,End_Position,Strand,Consequence,Variant_Classification,...,FILTER,Polyphen_Prediction,Polyphen_Score,SIFT_Prediction,SIFT_Score,SWISSPROT,n_depth,t_depth,Annotation_Status,mutationInCis_Flag
0,KRAS,3845.0,JHU,GRCh37,12,25398285,25398285,+,missense_variant,Missense_Mutation,...,undefined,probably_damaging,0.991,deleterious,0.04,NaN,NaN,1623.0,SUCCESS,False
1,BRAF,673.0,JHU,GRCh37,7,140453136,140453136,+,missense_variant,Missense_Mutation,...,undefined,probably_damaging,0.963,deleterious,0.00,NaN,NaN,1031.0,SUCCESS,False
2,EGFR,1956.0,JHU,GRCh37,7,55249071,55249071,+,missense_variant,Missense_Mutation,...,undefined,probably_damaging,1.000,deleterious,0.00,NaN,NaN,692.0,SUCCESS,False
3,TP53,7157.0,JHU,GRCh37,17,7577120,7577120,+,missense_variant,Missense_Mutation,...,undefined,possibly_damaging,0.643,tolerated,0.13,NaN,NaN,930.0,SUCCESS,False
4,NRAS,4893.0,JHU,GRCh37,1,115256529,115256529,+,missense_variant,Missense_Mutation,...,undefined,benign,0.251,tolerated,0.06,NaN,NaN,2277.0,SUCCESS,False